### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by mohammad5305** [mohammad5305/reberzug#1]
- [ ] finding WINDOWID in X
- [ ] tmux support (calculating x, y based on `tmux display`)
- [ ] setting up a tmux hook so every client gets the image
- [ ] wayland support
